### ISSUE TITLE
Help Required!!

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#14]
Wanted help to save the input of the gen-dockerfile cli tool to a Dockerfile

Comment if interested

**Comment by raulsoledispa** [comment]
Hello, I would like to help you.  Could you assign me the task please?.

I understand that the client input should generate the Dockerfile

**Comment by BRAVO68WEB** [comment]
For now check our repo and testing in your PC 

```
npm i -g gen-dockerfile
```

**Comment by raulsoledispa** [comment]
Please can you help me to update the _Hacktoberfest_ tag to _hacktoberfest_ as the PR submitted is invalid it is considered due to the tag not being recognized within the official Hacktoberfest site.

**Comment by BRAVO68WEB** [comment]
Yes i know my bad,
I was going to do so today

Thx to tell before
