### ISSUE TITLE
Add support for install of package

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#17]
Add support for install of package like NodeJS, python3, pip3, etc. according to OS Selection

Like :- if OS Selection is Ubuntu and Language type is Nodejs
ADD Statement:-  RUN apt install nodejs npm -y

**Comment by yrahul3910** [comment]
On it!

**Comment by BRAVO68WEB** [comment]
@yrahul3910 Check PR #18
