### ISSUE TITLE
Add Documentation 

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#20]
What should be Down !!
A proper and accurate documentation is required for **gen-dockerfile** 

**Additional context**
The documentation must contain example snippets and Screenshots 

How to proceed ?
Create a "Doc" forlder in main branch and add Documentation created by you ..

**Comment by raulsoledispa** [comment]
@BRAVO68WEB Hi, can you assign me to continue contributing please

**Comment by BRAVO68WEB** [comment]
Sure @raulsoledispa
