### ISSUE TITLE
ADD Framework Support Questions

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#21]
**What is to be down ?**
* Add question about, "Are you using any predefined framework ?" with ``y/n`` type
* If 'y', then ask where framework is it? {
- If Nodejs is Selected,
  - give options like Express, Hexo, Hugo, etc .. 
- If Python is Selected,
  - give options like Django, Flask, etc ..
* Else if ``n`` is selected, procced normally.

**More info ..**
``No need to add any other code, just add the questions!!`

**Comment by yohanesgultom** [comment]
Hi again. I tried to work on this issue as well to understand this project better. I've also pushed a PR. I hope you don't mind reviewing it. Thanks!

**Comment by BRAVO68WEB** [comment]
@yohanesgultom Awesome Work

Please your PR for Comments
