### ISSUE TITLE
Add Ruby Support

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#22]
**What's to be Done?**

* Add ``Ruby`` Language 
* Add Dependence installation support

**Comment by SerhatKayaa** [comment]
I would like to work on this ?

**Comment by BRAVO68WEB** [comment]
Sure

**Comment by BRAVO68WEB** [comment]
Go for it

**Comment by BRAVO68WEB** [comment]
@SerhatKayaa have you added the requested feature.

"If not would you like to withdraw yourself" as @Hyftar has already submitted the PR. Then i will unassign you and assign this issue to @Hyftar.

**Comment by BRAVO68WEB** [comment]
Ok Closing issue
