### ISSUE TITLE
Set App Name is WORKDIR 

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#23]
**What's to be down?**

Set Working Directory , the ``WORKDIR`` property in Dockerfile as the ``App name`` taken as input

**Comment by yohanesgultom** [comment]
Hi. It's an interesting project! This seems like a good first issue for me to learn how to contribute. I've pushed my PR. Let me know what you think. Thanks

**Comment by BRAVO68WEB** [comment]
Nice Works...
