### ISSUE TITLE
Add Ruby 

### ISSUE THREAD

**Issue by saurabhprasadsah** [DFTECHSDEVCENTER/gen-dockerfile#27]
****Describe** the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BRAVO68WEB** [comment]
@saurabhprasadsah ?

**Comment by BRAVO68WEB** [comment]
Added Ruby Supprot !!

**Comment by saurabhprasadsah** [comment]
okay
