### ISSUE TITLE
Add PHP lang Support

### ISSUE THREAD

**Issue by BRAVO68WEB** [DFTECHSDEVCENTER/gen-dockerfile#28]
# What's to be Done?

* Add PHP Language support
* Ask the User about entry point files 

## Example ..
Like if entry point file is "index.php"

```Dockerfile
..
RUN php -s localhost:{PORT_Exposed_by_User} index.php
..
```
OR

```Dockerfile
..
RUN php -s localhost:{PORT_Exposed_by_User} src/router.php
..
```

**Comment by BRAVO68WEB** [comment]
@yrahul3910 @raulsoledispa @yohanesgultom @Hyftar Interested?

**Comment by yohanesgultom** [comment]
This is interesting. Later we can also add optional `composer install` too as it is very common nowadays. But since my hacktoberfest quota has been fulfilled, I think I will give chance to other first 😅

**Comment by BRAVO68WEB** [comment]
OK sure

**Comment by BRAVO68WEB** [comment]
Fixed
